server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db_host}/${db_name}
    username: ${db_username}
    password: ${db_password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

openweather:
  base:
    url: http://api.openweathermap.org/data/2.5/weather
  apikey: ${apikey}